apiVersion: v2
name: blue-green-umbrella
description: A Helm chart for deploying multiple microservices with blue/green capabilities
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
- name: service-a
  version: "0.1.0"
  repository: "file://./charts/service-a"
- name: service-b
  version: "0.1.0"
  repository: "file://./charts/service-b" 