apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-b
  labels:
    app.kubernetes.io/name: service-b
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: service-b
    app.kubernetes.io/instance: {{ .Release.Name }}
    color: {{ coalesce .Values.deploymentColor ( .Values.global | default dict ).deploymentColor "blue" | quote }} 